services:
  - type: web
    name: codeigniter-app
    env: docker
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: apache2-foreground
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
    
databases:
  - name: postgres-db
    plan: free
